name=Soldered DE2120
version=1.0.0
author=Soldered
maintainer=Soldered <soldered@soldered.com>
sentence=Arduino library for the DE2120 Barcode Scanner.
paragraph=Supports reading 20 different 1D and 2D barcode symbologies over TTL UART. Provides methods for scanning, configuring reading modes, toggling the illumination light and aiming reticle, adjusting the reading area, and enabling or disabling individual symbology groups.
category=Sensors
url=https://www.soldered.com/
repository=https://github.com/SolderedElectronics/Soldered-Barcode-Scanner-DE2120-Arduino-Library
architectures=*
includes=DE2120-SOLDERED.h
